#!/usr/bin/env bash
# setup-gitsign-cache.sh
#
# Makes gitsign work for commits that have no TTY (the VS Code commit button)
# by routing signing through gitsign-credential-cache. Safe to re-run.
#
# Overrides:
#   GITSIGN_CACHE_VERSION  upstream release to download (default 0.17.1)
#   BIN_DIR                install directory (default ~/.local/bin)
#   GITSIGN_BIN            absolute path to gitsign if it is not on PATH
#   TUF_URL                TUF mirror of a private Sigstore instance such as RHTAS
set -euo pipefail

VERSION="${GITSIGN_CACHE_VERSION:-0.17.1}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
CACHE_BIN="$(command -v gitsign-credential-cache 2>/dev/null || echo "$BIN_DIR/gitsign-credential-cache")"
WRAPPER="$BIN_DIR/gitsign-wrapper"

# 1. Locate the real gitsign. Its absolute path is written into the wrapper,
#    because the VS Code extension host can have a different PATH than a terminal.
GITSIGN_BIN="${GITSIGN_BIN:-$(command -v gitsign || true)}"
if [ -z "$GITSIGN_BIN" ] || [ ! -x "$GITSIGN_BIN" ]; then
  echo "gitsign not found. Re-run with GITSIGN_BIN=/absolute/path/to/gitsign" >&2
  exit 1
fi

mkdir -p "$BIN_DIR"

# 2. Download gitsign-credential-cache from the upstream release, if missing.
if [ ! -x "$CACHE_BIN" ]; then
  case "$(uname -m)" in
    x86_64)  arch=amd64 ;;
    aarch64) arch=arm64 ;;
    *) echo "no upstream linux build for $(uname -m)" >&2; exit 1 ;;
  esac
  asset="gitsign-credential-cache_${VERSION}_linux_${arch}"
  base="https://github.com/sigstore/gitsign/releases/download/v${VERSION}"
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  curl -fsSL -o "$tmp/$asset" "$base/$asset"
  curl -fsSL -o "$tmp/checksums.txt" "$base/checksums.txt"
  (cd "$tmp" && sha256sum --ignore-missing -c checksums.txt)
  install -m 0755 "$tmp/$asset" "$CACHE_BIN"
fi

# 3. Trust root. With the cache, gitsign checks the certificate against the
#    Fulcio root from TUF. Plain signing skips that check, so a workspace can
#    sign from a terminal and still lack the root of a private instance.
tuf_url="${TUF_URL:-}"
if [ -z "$tuf_url" ]; then
  fulcio="$(git config --get gitsign.fulcio || true)"
  fulcio="${fulcio%/}"
  case "$fulcio" in
    "") ;;  # public Sigstore: nothing to initialise
    *fulcio-server*) tuf_url="${fulcio/fulcio-server/tuf}" ;;
    *) echo "Cannot derive the TUF URL from $fulcio. Re-run with TUF_URL=https://..." >&2; exit 1 ;;
  esac
fi
if [ -n "$tuf_url" ] && ! grep -qF "$tuf_url" "$HOME/.sigstore/root/remote.json" 2>/dev/null; then
  "$GITSIGN_BIN" initialize --mirror="$tuf_url" --root="$tuf_url/root.json"
fi

# 4. Write the wrapper that git calls instead of gitsign.
{
  printf '#!/bin/sh\n'
  printf '# Generated by setup-gitsign-cache.sh. Called by git as gpg.x509.program.\n'
  printf 'GITSIGN_BIN=%q\n' "$GITSIGN_BIN"
  cat <<'EOF'
sock="${XDG_CACHE_HOME:-$HOME/.cache}/sigstore/gitsign/cache.sock"
# Use the cache only while its socket exists; otherwise behave like plain gitsign.
[ -S "$sock" ] && export GITSIGN_CREDENTIAL_CACHE="$sock"
# Without a TTY, gitsign errors are only visible in this file.
export GITSIGN_LOG="${GITSIGN_LOG:-$HOME/gitsign.log}"
exec "$GITSIGN_BIN" "$@"
EOF
} > "$WRAPPER"
chmod 0755 "$WRAPPER"

# 5. Point git at the wrapper.
git config --global gpg.x509.program "$WRAPPER"

effective="$(git config --get gpg.x509.program || true)"
if [ "$effective" != "$WRAPPER" ]; then
  echo "WARNING: another config level overrides gpg.x509.program:" >&2
  git config --show-origin --get-all gpg.x509.program >&2 || true
fi

echo "gitsign:  $GITSIGN_BIN"
echo "cache:    $CACHE_BIN ($("$CACHE_BIN" --version 2>/dev/null || echo 'version unknown'))"
echo "wrapper:  $WRAPPER"
echo "Next: run '$CACHE_BIN' in the foreground of its own terminal tab."
